disable_ray: false
max_tokens: 4096
models:
- codellama/CodeLlama-34b-Instruct-hf
num_gpus: 8
num_tensor_parallel_workers:
- 1
- 2
- 4
- 8
output_dir: profiling_outputs/mlp/2025-09-26_13-41-25
profile_method: record_function
