disable_ray: false
max_tokens: 4096
models:
- meta-llama/Llama-2-7b-hf
num_gpus: 8
num_tensor_parallel_workers:
- 1
- 2
- 4
- 8
output_dir: profiling_outputs/mlp/2025-09-28_00-36-58
profile_method: record_function
